# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:
  - unit-test
  - rebuild-container

getVersion:
  stage: .pre
  script:
    - echo -e "\nTAG=$CI_COMMIT_TAG" >> .env
    - echo -e "COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA" >> .env
  artifacts:
    expire_in: never
    paths:
      - ./
    reports:
      dotenv:
        - .env

unitTestJob:
  stage: unit-test
  only:
    - tags
  except:
    - branches
  variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - echo "Start unit-test..."
    - /home/gitlab-runner/venv3.12/bin/pytest -v

rebuildContainerJob:
  stage: rebuild-container
  needs:
    - job: getVersion
      artifacts: true
  only:
    - tags
  except:
    - branches
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_UPDATE_FLAGS: --remote --merge
  script:
    - echo "Rebuild container..."
    # - echo "$USER"
    - docker compose -p $(cat .env | grep 'CONTAINER_ID=[0-9]' | cut -d '=' -f2 | tr -d '\r\n')_$(cat .env | grep 'CONTAINER_NAME=[a-z_]' | cut -d '=' -f2 | tr -d '\r\n') down --rmi local
    - docker compose -p $(cat .env | grep 'CONTAINER_ID=[0-9]' | cut -d '=' -f2 | tr -d '\r\n')_$(cat .env | grep 'CONTAINER_NAME=[a-z_]' | cut -d '=' -f2 | tr -d '\r\n') up -d
  after_script:
    - rm -rf *