"""Update

Revision ID: 8402516e24bd
Revises: d66dde47977d
Create Date: 2026-03-21 19:09:46.235169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8402516e24bd'
down_revision: Union[str, Sequence[str], None] = 'd66dde47977d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bots')
    op.drop_table('gate_key')
    op.drop_table('telegram_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_token',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('t_user_id', sa.BIGINT(), nullable=False),
    sa.Column('token', sa.TEXT(), nullable=False),
    sa.Column('bot_name', sa.TEXT(), nullable=False),
    sa.Column('bot_active', sa.BOOLEAN(), nullable=True),
    sa.Column('unix_time', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gate_key',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('t_user_id', sa.BIGINT(), nullable=False),
    sa.Column('key', sa.TEXT(), nullable=False),
    sa.Column('secret', sa.TEXT(), nullable=False),
    sa.Column('expire', sa.INTEGER(), nullable=False),
    sa.Column('unix_time', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bots',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
