"""Init migration

Revision ID: d66dde47977d
Revises: 
Create Date: 2026-03-21 19:04:32.227649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd66dde47977d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_pamp_stocks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('currency_pair', sa.TEXT(), nullable=False),
    sa.Column('last', sa.TEXT(), nullable=True),
    sa.Column('lowest_ask', sa.TEXT(), nullable=True),
    sa.Column('highest_bid', sa.TEXT(), nullable=True),
    sa.Column('change_percentage', sa.TEXT(), nullable=True),
    sa.Column('change_utc0', sa.TEXT(), nullable=True),
    sa.Column('change_utc8', sa.TEXT(), nullable=True),
    sa.Column('base_volume', sa.TEXT(), nullable=True),
    sa.Column('quote_volume', sa.TEXT(), nullable=True),
    sa.Column('high_24h', sa.TEXT(), nullable=True),
    sa.Column('low_24h', sa.TEXT(), nullable=True),
    sa.Column('etf_net_value', sa.TEXT(), nullable=True),
    sa.Column('etf_pre_net_value', sa.TEXT(), nullable=True),
    sa.Column('etf_pre_timestamp', sa.BIGINT(), nullable=True),
    sa.Column('etf_leverage', sa.TEXT(), nullable=True),
    sa.Column('algorithm_id', sa.SMALLINT(), nullable=False),
    sa.Column('t_user_id', sa.BIGINT(), nullable=False),
    sa.Column('bot_name', sa.TEXT(), nullable=False),
    sa.Column('unix_time', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arithmetic_mean',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('t_user_id', sa.BIGINT(), nullable=False),
    sa.Column('seconds', sa.REAL(), nullable=False),
    sa.Column('times', sa.BIGINT(), nullable=False),
    sa.Column('bot_name', sa.TEXT(), nullable=False),
    sa.Column('algorithm_id', sa.INTEGER(), nullable=False),
    sa.Column('unix_time', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gate_key',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('t_user_id', sa.BIGINT(), nullable=False),
    sa.Column('key', sa.TEXT(), nullable=False),
    sa.Column('secret', sa.TEXT(), nullable=False),
    sa.Column('expire', sa.INTEGER(), nullable=False),
    sa.Column('unix_time', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('t_user_id', sa.BIGINT(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('currency', sa.TEXT(), nullable=False),
    sa.Column('unix_time', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_token',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('t_user_id', sa.BIGINT(), nullable=False),
    sa.Column('token', sa.TEXT(), nullable=False),
    sa.Column('bot_name', sa.TEXT(), nullable=False),
    sa.Column('bot_active', sa.BOOLEAN(), nullable=True),
    sa.Column('unix_time', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('t_user_id', sa.BIGINT(), nullable=False),
    sa.Column('t_chat_id', sa.BIGINT(), nullable=False),
    sa.Column('t_first_name', sa.TEXT(), nullable=True),
    sa.Column('t_last_name', sa.TEXT(), nullable=True),
    sa.Column('t_username', sa.TEXT(), nullable=True),
    sa.Column('t_is_bot', sa.BOOLEAN(), nullable=True),
    sa.Column('t_language_code', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('registr', sa.BOOLEAN(), nullable=True),
    sa.Column('varific', sa.BOOLEAN(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.Column('ban', sa.BOOLEAN(), nullable=True),
    sa.Column('unix_time', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('telegram_token')
    op.drop_table('note')
    op.drop_table('gate_key')
    op.drop_table('bots')
    op.drop_table('arithmetic_mean')
    op.drop_table('all_pamp_stocks')
    # ### end Alembic commands ###
